# Generated by Django 6.0.3 on 2026-03-18 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='estates', to='estate.estate_agent', verbose_name='Agent'),
        ),
    ]
